### ISSUE TITLE
Merge Volley dmg for hunters.

### ISSUE THREAD

**Issue by Alkotronikk** [Barsoomx/xCT_Plus_wotlk#2]
I'd like to see Volley damage being merged. I already managed to merge it by adding a following line into the hunter section of merge.lua:

```
  [58433]  = CreateMergeSpellEntry("HUNTER", .5),      -- Volley
```

The 0.5 reasoning is that I can see each tick separately.

**Comment by Barsoomx** [comment]
Thanks! Added it
