### ISSUE TITLE
[Hunter] Explosive trap is missing an icon.

### ISSUE THREAD

**Issue by Alkotronikk** [Barsoomx/xCT_Plus_wotlk#3]
The Explosive Trap is missing an icon - both the instant component and the aoe over the time component.

The icon should be taken either from the spell itself or the physical (red border) debuff of the effect on targets.

let me know if I can help with debugging.

**Comment by Barsoomx** [comment]
Ignite damage also misses an icon, I'll look into it tomorrow, i think this section needs a bit of rewrite
![изображение](https://user-images.githubusercontent.com/54457590/122692349-1c9fba00-d23d-11eb-8a5e-02fa88103f60.png)

```lua
Message: Interface\AddOns\xCT+\modules\combattext.lua:356: GetSpellTexture(): Invalid spell slot
Time: 06/20/21 23:01:26
Count: 6
Stack: (tail call): ?
[C]: ?
[C]: in function GetSpellTexture'
Interface\AddOns\xCT+\modules\combattext.lua:356: in function GetSpellTextureFormatted'
Interface\AddOns\xCT+\modules\combattext.lua:1408: in function `?'
Interface\AddOns\xCT+\modules\combattext.lua:323: in function <Interface\AddOns\xCT+\modules\combattext.lua:317>
```
may be related also, not sure, just to remember

**Comment by Alkotronikk** [comment]
When I turn on the IDs showing, the Explosive trap is shown as ID `49065` whereas the actual spell in my spellbook is `49067`.

So it might require to have a mapping of spell effects to corresponding spells to get the icon.

I tried adding the following into the _GetSpellTextureFormatted()_ function right after _spellName_ definition : 

```
    if (spellID == 49065) then
      spellName = GetSpellInfo(49067)
    end    
```

Which for me works just fine now, but I don't know what would a correct implementation would be.
